services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shortgenerator-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    restart: unless-stopped
    networks:
      - app-network

  backend:
    # profiles: ["backend"]
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shortgenerator-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
    networks:
      - app-network

  database:
    profiles: ["database"]
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: shortgenerator-database
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
      - ./database/backups:/backups
    env_file:
      - ./database/env/postgres.env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database-data:
